---
AWSTemplateFormatVersion: "2010-09-09"
Description: "The resources for the even driven architecture example"
Resources:
  ImageBucket:
    Type: AWS::S3::Bucket
  ImageMetadataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: ImageId
          AttributeType: S
      KeySchema:
        - AttributeName: ImageId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  ImageProcessorFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.9
      Handler: image_processor.lambda_handler
      CodeUri: s3://[S3_NAME]/image_processor.zip
      Policies:
        - S3ReadPolicy
        - RekognitionAccessPolicy
        - DynamoDBWritePolicy
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: ImageMetadataTable
  UploadListenerFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: nodejs14.x
      Handler: upload_listener.handler
      CodeUri: s3://[S3_NAME]/upload_listener.zip
      Policies:
        - LambdaInvokePolicy
      Environment:
        Variables:
          IMAGE_PROCESSOR_FUNCTION_NAME: ImageProcessorFunction
  ImageBucketNotificationConfiguration:
    Type: AWS::S3::BucketNotificationConfiguration
    Properties:
      Bucket: ImageBucket
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: UploadListenerFunction.Arn
